config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "flashcards#index"
  resources :flashcards do
    get :random, on: :collection
    get :search, on: :member
  end
  resource :search, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
    validates :question, presence: true
    validates :answer, presence: true

    def self.find_random
        min = Flashcard.minimum(:id)
        max = Flashcard.maximum(:id)
        raise ActiveRecord::RecordNotFound if min.nil? || max.nil? 

        id = rand(min..max)
        @flashcard = Flashcard.find_or_next(id)
    end

    def self.find_or_next(id)
        card = where('id >= ?', id).limit(1).first
        raise ActiveRecord::RecordNotFound if card.nil?
        
        card
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
    before_action :set_flashcard, only: [:show, :search, :edit, :update, :destroy]

    def index
        @flashcards = Flashcard.all
    end

    def show; end

    def random
        @flashcard = Flashcard.find_random

        redirect_to flashcard_path(@flashcard)
    rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert: 'No flashcards to quiz'
    end

    def search
        correct = @flashcard.answer.downcase == params[:guess].downcase
        message = correct ? 'Correct!' : 'Incorrect!'
        redirect_to flashcard_path(@flashcard), notice: message
    end
    
    def new
        @flashcard = Flashcard.new
    end

    def create
        @flashcard = Flashcard.new(flashcard_params)

        if @flashcard.save
            redirect_to root_path, notice: 'Flashcard created successfully'
        else
            render :new, alert: "Flashcard not created: #{flashcard.errors.full_messages.to_sentence}"
        end
    end

    def edit; end

    def update
        if @flashcard.update(flashcard_params) 
            redirect_to flashcard_path(@flashcard), notice: 'Flashcard updated successfully'
        else
            render :edit, alert: "Flashcard not updated: #{flashcard.errors.full_messages.to_sentence}"
        end
    end
    
    def destroy
        if @flashcard.destroy
            redirect_to root_path, notice: 'Flashcard deleted successfully'
        else
            redirect_to root_path, alert: "Flashcard not deleted: #{flashcard.errors.full_messages.to_sentence}"
        end
    end

    private

    def flashcard_params
        params.require(:flashcard).permit(:question, :answer)
    end

    def set_flashcard
        @flashcard = Flashcard.find(params[:id])
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def show
        if params[:query].present?
            @flashcards = Flashcard.where("question ilike ?", "%#{params[:query]}%").limit(5)
        else
            @flashcards = Flashcard.all.limit(5)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flashcards/_flashcard.html.erb
<div class="flashcard">
    <%= link_to flashcard.question, flashcard_path(flashcard) %>
    <div class="flashcard__actions">
        <%= button_to "Delete", flashcard_path(flashcard), method: :delete, class: "btn btn--light" %>
        <%= link_to "Edit", edit_flashcard_path(flashcard), class: "btn btn--light" %>
    </div>
</div>

<% if current_page?(flashcard_path(flashcard)) %>
    <%= form_tag("/flashcards/#{flashcard.id}/search", method: :get) do %>
        <%= label_tag :guess %>
        <%= text_field_tag :guess %>
        <%= submit_tag('Submit', class: "btn btn--secondary" ) %>
    <% end %>

    <div class='container' data-controller="toggle">
        <div class='flashcard__btn'>
            <span data-action="click->toggle#toggle" class="btn btn--secondary" id='reveal-btn'>Reveal</span>
        </div>
        <div data-toggle-target="answer" id='answer' hidden>
            <p class="flashcard__answer"><%= flashcard.answer %></p>
        </div>
    </div>
<% end %>

app/views/flashcards/_form.html.erb
<%= form_with(model: @flashcard, local: true, class: "form") do |form| %>
    <div class="field">
        <%= form.label :question %>
        <%= form.text_field :question %>
    </div>

    <div class="field">
        <%= form.label :answer %>
        <%= form.text_field :answer %>
    </div>
    <div class="actions">
        <%= form.submit "Submit", class: "btn btn--secondary" %>
    </div>
<% end %>

app/views/flashcards/edit.html.erb
<main class='container'>
    <div class='header'>
        <h3>Update flashcard</h3>
    </div>

    <%= render "form", flashcard: @flashcard %>
</main>

app/views/flashcards/index.html.erb
<main class='container'>
    <%= render @flashcards %>
</main>

app/views/flashcards/new.html.erb
<main class='container'>
    <div class='header'>
        <h3>Create a new flashcard</h3>
    </div>

    <%= render "form", flashcard: @flashcard %>
</main>

app/views/flashcards/show.html.erb
<main class='container'>
    <%= render @flashcard %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestYourself</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class='container'>
      <div class='header'>

        <h1>Flashcards</h1>
        <%= link_to 'Quiz me!', random_flashcards_path, class: "btn btn--primary"  %>
        <% if @flashcard %>
          <%= link_to sanitize("&larr; Back to flashcards"), root_path %>
        <% else %>
          <%= link_to "New flashcard", new_flashcard_path, class: "btn btn--primary" %>
        <% end %>
      </div>
    </header>

    <div class="flash-container">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>

    <main class='container'>

      <%= yield %>

      <dialog class='ksearch' data-controller="dialog" data-action="keydown.meta+k@window->dialog#open">
        <%# <form method="dialog", class='ksearch__actions'>
          <button class="btn btn--dark">Close</button>
        </form> %>
        
        <%= form_with url: search_path, method: :get, data: { controller: "autosubmit", autosubmit_delay_value: 300, turbo_frame: :search } do |f| %>
          <%= f.search_field :query, autofocus: true, data: { action: "autosubmit#submit" } %>
        <% end %>

        <%= turbo_frame_tag :search, loading: :lazy, src: search_path %>
      </dialog>
    </main>

  </body>
</html>

app/views/searches/show.html.erb
<%= turbo_frame_tag :search do %>
    <% if @flashcards.any? %>
    <ul>
        <% @flashcards.each do |card| %>
        <li>
            <%= link_to card.question, card, data: { turbo_frame: "_top" } %>
        </li>
        <% end %>
    </ul>
    <% else %>
        <p>No results</p>
    <% end %>
<% end %>